.eslintrc, examples/app/test/app_test.js, examples/app/test/config_test.js, examples/app/test/di_test.js, examples/app/test/redis_test.js, examples/app/test/services_test.js, examples/app/test/some_test.js, lib/index.js, lib/test/initialize_tests.js
namespace instead
Resolves #28
=> + Removed globals: app, log, config, container and introduced `Q`

examples/app/test/pubsub_test.js, lib/pubsub/pubsub.js
=> * Hub endpoint is now configurable

examples/app/test/config_test.js, lib/config.js
=> + Configuration provider

examples/app/test/di_test.js, examples/app/test/services_test.js, initializers/services.js, lib/di/container.js
* Fixed services resolution by service name (without `services:`
* namespace), resolves #50
=> + Implemented aliases in DI (resolves #51)

examples/app/initializers/app_load.js, examples/app/test/app_test.js, examples/app/test/redis_test.js, examples/app/test/services_test.js, examples/app/test/stats_test.js, initializers/http_server.js, initializers/jobs.js, initializers/pubsub.js, initializers/request.js, initializers/run_services.js, lib/app.js, lib/index.js, lib/services_loader.js, package.json, services/http_server.js, services/pubsub.js, services/redis.js, services/request.js, services/stats.js
* Register services as camel case (resolves #54)
* App initializers should run after services registration - resolves #53
+ Add async events support - resolves #56
+ Make `app` EventEmitter - resolves #55
=> DI bugfixes

examples/app/test/app_test.js, examples/app/test/di_test.js, lib/di/container.js, lib/di/metadata.js, lib/http_server/quadro_router.js, lib/http_server/routes.js, lib/http_server/server.js, lib/test/test.js, package.json, services/http_server.js
* Refactored httpServer registration
=> + Added configuration for HTTP connection response timeout

.circleci/config.yml, examples/app/test/aws_test.js, examples/app/test/config_test.js, lib/config/config.js, lib/config/dynamodb_provider.js, lib/index.js, services/aws.js, services/dynamodb_config_provider.js
=> Dynamodb config provider

examples/app/services/nested/svc.js, examples/app/test/di_test.js, examples/app/test/services_test.js, lib/di/metadata.js, lib/services_loader.js
+ Implemented namespaced dependencies resolving (resolves #115)
=> + Implemented nested services

CHANGELOG.md, docs/event_emitter.md, docs/repl.md, examples/app/test/aws_test.js, lib/index.js, lib/initializers.js, lib/profiler.js, lib/repl/repl.js, package.json
- Make sure initializers finished running before continuing application execution
- Write EventEmitter doc (resolves #133)
- When a profiler-wrapped function throws an error - the error should bubble up
=> - Implemented REPL (resolves #129)

CHANGELOG.md, examples/app/test/some_test.js, package.json
until https://github.com/domenic/chai-as-promised/pull/157 is merged.
=> Workaround https://github.com/domenic/chai-as-promised/issues/198

CHANGELOG.md, docs/pubsub.md, examples/app/config/test/service.yml, examples/app/test/pubsub/pubsub_consumer_test.js, package.json, services/pubsub/hub_message_context.js, services/pubsub/hub_message_processor.js, services/pubsub/hub_stats.js, services/pubsub/rabbit_message_adapter.js
1. Fixed issues with message context
2. Made all the configs optional except for service name, rabiitmq connection url and mongo connection url
=> Pubsub changes

CHANGELOG.md, docs/models.md, examples/app/test/odbm/model_test.js, examples/app/test/odbm/repository_test.js, lib/odbm/adapters/mongo.js, lib/odbm/model.js, lib/odbm/repository.js, package.json
=> + ODBM: model.isNew()

lib/http_server/server.js
increased limits to 10mb, defaults were:  jsonLimit 1mb, formLimit 56…kb and textLimit 56kb
more info: https://github.com/dlau/koa-body
=> EPS-211 unable to upload bigger file

services/pubsub.js, services/pubsub/hub_message_processor.js, services/pubsub/hub_stats.js
Added prometheus support for the pubsub service.
This is pending #303
=> PubSub Prometheus integration

examples/app/test/services/mongo_test.js, services/mongo.js, services/prometheus.js, services/pubsub.js, services/pubsub/hub_message_processor.js
Fast-following updates to Quadro v1.1.0
=> Prometheus cleanup

lib/test/initializers/sinon.js
=> Updates p2

initializers/worker_gague.js, lib/http_server/server.js, services/mongo.js, services/pubsub/hub_message_processor.js
=> Metrics improvements

lib/http_server/server.js
Cannot believe it was as simple as moving the path to after the next statement
=> OPT-303 HTTP paths

services/mongo.js
=> #400 metrics bugfix

services/pubsub/rabbitmq_channel.js
The channel returns a boolean to indicate whether the producer should wait, not to indicate if the message failed to reach RMQ. Removing the retry logic prevents duplicate messages.
It also highlights the fact that we're not really waiting for confirmation on published events before completing our subscribed events. Not sure how to solve that, but we can settle for this for now.
=> Remove retry logic from RMQ publish function
